"""Core data models, security enums, and schemas for TraceGuard AI."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid
from pydantic import BaseModel, ConfigDict, Field


class PolicyDecision(str, Enum):
    """Deterministic security decisions generated by the Action Firewall."""
    ALLOW = "ALLOW"
    ASK_USER = "ASK_USER"
    BLOCK = "BLOCK"


class SensitiveActionType(str, Enum):
    """Categorization of sensitive tool actions requiring firewall inspection."""
    PAYMENT = "PAYMENT"
    EXTERNAL_EMAIL = "EXTERNAL_EMAIL"
    DATABASE_WRITE = "DATABASE_WRITE"
    FILE_DELETE = "FILE_DELETE"
    DATA_EXPORT = "DATA_EXPORT"
    BENEFICIARY_CHANGE = "BENEFICIARY_CHANGE"
    READ_DOCUMENT = "READ_DOCUMENT"


class TaintStatus(str, Enum):
    """Provenance taint status tracking untrusted document sources."""
    CLEAN = "CLEAN"
    TAINTED = "TAINTED"
    SUSPICIOUS = "SUSPICIOUS"
    UNTRUSTED = "UNTRUSTED"
    TRUSTED = "TRUSTED"


class TrustLevel(str, Enum):
    """Provenance trust level for data origins."""
    TRUSTED_INTERNAL = "TRUSTED_INTERNAL"
    UNTRUSTED_EXTERNAL = "UNTRUSTED_EXTERNAL"


class SourceType(str, Enum):
    """Origin category of ingested inputs."""
    INVOICE = "INVOICE"
    EMAIL = "EMAIL"
    WEB = "WEB"
    RAG = "RAG"
    USER = "USER"
    DOCUMENT = "DOCUMENT"
    PDF = "PDF"
    DOCX = "DOCX"
    CSV = "CSV"
    JSON = "JSON"
    XML = "XML"
    HTML = "HTML"
    MARKDOWN = "MARKDOWN"
    IMAGE = "IMAGE"
    UNKNOWN = "UNKNOWN"


class HealthResponse(BaseModel):
    """API health check response schema."""
    status: str = Field(default="ok", description="Service health status")
    app: str = Field(..., description="Application name")
    version: str = Field(..., description="Application version")
    environment: str = Field(..., description="Operating environment")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp of the health check in UTC",
    )


class AuditEvent(BaseModel):
    """Immutable audit record for security decisions."""
    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the audit event",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the decision was recorded in UTC",
    )
    source_id: str = Field(
        ...,
        description="Origin identifier of the data/request (e.g., file ID, user session)",
    )
    intent_id: Optional[str] = Field(
        default=None,
        description="Identifier of the User Intent Contract governing this request",
    )
    action_type: SensitiveActionType = Field(
        ...,
        description="Type of sensitive action requested",
    )
    decision: PolicyDecision = Field(
        ...,
        description="Final deterministic firewall decision",
    )
    reason: str = Field(
        ...,
        description="Explainable rationale for the policy decision",
    )
    taint_status: TaintStatus = Field(
        default=TaintStatus.CLEAN,
        description="Provenance taint status at time of decision",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Sanitized non-sensitive contextual metadata",
    )


class FileValidationResult(BaseModel):
    """Structured result of secure file validation."""
    is_valid: bool = Field(..., description="Whether the file passed all validation checks")
    error_message: Optional[str] = Field(default=None, description="Reason for validation failure if invalid")
    sanitized_name: Optional[str] = Field(default=None, description="Safe generated filename if valid")
    original_name: str = Field(..., description="Original client-supplied filename")
    file_size_bytes: int = Field(default=0, description="Validated file size in bytes")
    extension: str = Field(default="", description="Normalized file extension")


class ErrorResponse(BaseModel):
    """Structured, secure error response that does not expose internal stack traces."""
    error: str = Field(..., description="High-level error description")
    detail: Optional[str] = Field(default=None, description="Sanitized client-safe detail")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the error",
    )
    request_id: Optional[str] = Field(default=None, description="Correlation ID for error tracing")


# --- Phase 2 Models ---

class SourceRecord(BaseModel):
    """Provenance tracking record for an ingested external document."""
    source_id: str = Field(
        default_factory=lambda: f"SRC-{uuid.uuid4().hex[:8].upper()}",
        description="Unique provenance identifier for the source",
    )
    source_type: SourceType = Field(default=SourceType.INVOICE, description="Source category")
    filename: str = Field(..., description="Sanitized internal filename")
    original_filename: str = Field(..., description="Original user-provided filename")
    content_hash: str = Field(..., description="SHA-256 cryptographic digest of raw content")
    trust_level: TrustLevel = Field(
        default=TrustLevel.UNTRUSTED_EXTERNAL,
        description="Trust classification of origin",
    )
    taint_status: TaintStatus = Field(
        default=TaintStatus.UNTRUSTED,
        description="Current taint status of the source",
    )
    raw_text: str = Field(..., description="Safely extracted plain text content")
    extracted_fields: Dict[str, Any] = Field(
        default_factory=dict,
        description="Extracted key-value business fields",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp in UTC",
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata tags")


class InjectionDetectionResult(BaseModel):
    """Structured output from prompt-injection heuristic detection."""
    detected: bool = Field(..., description="Whether prompt injection patterns were discovered")
    risk_level: str = Field(..., description="Risk tier: NONE | LOW | MEDIUM | HIGH | CRITICAL")
    matched_patterns: List[str] = Field(
        default_factory=list,
        description="Specific injection patterns identified",
    )
    reason: str = Field(..., description="Explainable description of detection finding")


class IntentContract(BaseModel):
    """
    Immutable User Intent Contract.
    
    Establishes the authorized boundary of user instructions.
    External documents cannot modify or expand this contract.
    """
    model_config = ConfigDict(frozen=True)

    intent_id: str = Field(
        default_factory=lambda: f"INT-{uuid.uuid4().hex[:8].upper()}",
        description="Unique intent contract identifier",
    )
    user_goal: str = Field(..., description="User stated objective")
    allowed_actions: List[str] = Field(
        ...,
        description="Explicit list of tool actions authorized by user",
    )
    source: str = Field(default="USER_EXPLICIT", description="Origin of intent contract")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp in UTC",
    )


class PlanStep(BaseModel):
    """Single step in an agent plan evaluated by the Action Firewall."""
    step_id: str = Field(
        default_factory=lambda: f"STP-{uuid.uuid4().hex[:6].upper()}",
        description="Unique step identifier",
    )
    action_name: str = Field(..., description="Tool action name")
    action_type: SensitiveActionType = Field(
        ...,
        description="Sensitive action classification category",
    )
    arguments: Dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments passed to the tool",
    )
    is_tainted: bool = Field(
        default=False,
        description="True if step arguments or logic derive from tainted content",
    )
    taint_source_id: Optional[str] = Field(
        default=None,
        description="Source ID originating the taint",
    )
    taint_reason: Optional[str] = Field(
        default=None,
        description="Reason why this step is tainted",
    )
    rationale: str = Field(..., description="Agent reasoning for proposed step")


class AgentPlan(BaseModel):
    """Structured mock agent plan before firewall inspection."""
    plan_id: str = Field(
        default_factory=lambda: f"PLN-{uuid.uuid4().hex[:8].upper()}",
        description="Unique plan identifier",
    )
    intent_id: str = Field(..., description="Associated Intent Contract ID")
    source_id: str = Field(..., description="Associated Document Source ID")
    steps: List[PlanStep] = Field(default_factory=list, description="Ordered plan steps")
    summary: str = Field(..., description="High-level plan summary")
    has_tainted_steps: bool = Field(
        default=False,
        description="Whether any plan step is flagged as tainted",
    )


class FirewallEvaluation(BaseModel):
    """Deterministic security evaluation output for a single action step."""
    evaluation_id: str = Field(
        default_factory=lambda: f"EVAL-{uuid.uuid4().hex[:8].upper()}",
        description="Unique evaluation identifier",
    )
    step_id: str = Field(..., description="Target plan step ID")
    action_name: str = Field(..., description="Action name evaluated")
    action_type: SensitiveActionType = Field(..., description="Action category")
    decision: PolicyDecision = Field(..., description="Deterministic firewall decision")
    reason: str = Field(..., description="Explainable rationale")
    violated_constraints: List[str] = Field(
        default_factory=list,
        description="List of security constraints violated (if any)",
    )
    audit_event_id: str = Field(..., description="Associated immutable audit event ID")


class ToolExecutionResult(BaseModel):
    """Safe simulated execution result from mock tools."""
    tool_name: str = Field(..., description="Name of the mock tool")
    executed: bool = Field(..., description="Whether the tool actually executed")
    decision: PolicyDecision = Field(..., description="Firewall authorization decision")
    firewall_evaluation_id: Optional[str] = Field(
        default=None,
        description="Firewall evaluation token",
    )
    result_data: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Simulated mock execution output",
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Reason if execution was skipped or blocked",
    )


# --- Phase 3 Models ---

class VendorRecord(BaseModel):
    """Approved mock vendor registry record."""
    vendor_id: str = Field(..., description="Unique vendor ID, e.g., V001")
    name: str = Field(..., description="Primary vendor name")
    aliases: List[str] = Field(default_factory=list, description="Known naming variations")
    approved_beneficiary: str = Field(..., description="Whitelisted bank account/IBAN")
    status: str = Field(default="ACTIVE", description="Vendor status: ACTIVE | INACTIVE")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Record registration timestamp",
    )


class BusinessVerificationResult(BaseModel):
    """Structured result of vendor master & beneficiary account verification."""
    verification_id: str = Field(
        default_factory=lambda: f"BV-{uuid.uuid4().hex[:8].upper()}",
        description="Unique verification check ID",
    )
    source_id: str = Field(..., description="Source document ID verified")
    vendor_id: Optional[str] = Field(default=None, description="Matched vendor ID")
    vendor_name: Optional[str] = Field(default=None, description="Extracted vendor name")
    vendor_found: bool = Field(..., description="Whether vendor was found in approved master")
    vendor_status: str = Field(
        default="NOT_FOUND",
        description="Status: ACTIVE | INACTIVE | NOT_FOUND",
    )
    beneficiary_match: bool = Field(
        ...,
        description="Whether invoice beneficiary matches approved vendor beneficiary",
    )
    expected_beneficiary: Optional[str] = Field(
        default=None,
        description="Beneficiary account on file in vendor master",
    )
    actual_beneficiary: Optional[str] = Field(
        default=None,
        description="Beneficiary account stated in invoice",
    )
    risk_level: str = Field(
        default="NONE",
        description="Business risk tier: NONE | MEDIUM | HIGH | CRITICAL",
    )
    reasons: List[str] = Field(default_factory=list, description="Verification rationale bullets")


class EvidenceNode(BaseModel):
    """Node in the explainable evidence graph."""
    node_id: str = Field(..., description="Unique node identifier")
    node_type: str = Field(..., description="Category: INTENT | SOURCE | INJECTION | TAINT | VENDOR | PLAN | FIREWALL | RECOVERY")
    label: str = Field(..., description="Human-readable node label")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Contextual attributes")


class EvidenceEdge(BaseModel):
    """Causal relationship edge in the explainable evidence graph."""
    source_id: str = Field(..., description="Originating node ID")
    target_id: str = Field(..., description="Target node ID")
    relationship: str = Field(..., description="Causal description, e.g., constrained_by, detected_mismatch")


class EvidenceGraph(BaseModel):
    """Directed explainability graph tracing the decision lineage."""
    nodes: List[EvidenceNode] = Field(default_factory=list, description="Graph nodes")
    edges: List[EvidenceEdge] = Field(default_factory=list, description="Causal relationship edges")
    summary: str = Field(..., description="High-level narrative of decision provenance")


class RecoveryAction(BaseModel):
    """Deterministic safe next step recommendation when actions are blocked or gated."""
    action_type: str = Field(
        ...,
        description="Action: REQUEST_USER_CONFIRMATION | REQUEST_VENDOR_VERIFICATION | CREATE_VERIFICATION_TICKET | CANCEL_ACTION | PROCEED_SAFELY",
    )
    message: str = Field(..., description="Explainable recommendation message")
    requires_firewall_reentry: bool = Field(
        default=True,
        description="Guarantees any subsequent retry MUST pass through Action Firewall",
    )
    suggested_next_steps: List[str] = Field(
        default_factory=list,
        description="Safe operational instructions",
    )


class PipelineRunResult(BaseModel):
    """End-to-end trace of a complete TraceGuard AI pipeline run (Phase 3)."""
    run_id: str = Field(
        default_factory=lambda: f"RUN-{uuid.uuid4().hex[:8].upper()}",
        description="Pipeline execution identifier",
    )
    source: SourceRecord = Field(..., description="Ingested source document metadata")
    injection_result: InjectionDetectionResult = Field(
        ...,
        description="Injection analysis result",
    )
    intent: IntentContract = Field(..., description="Immutable user intent contract")
    plan: AgentPlan = Field(..., description="Agent plan before firewall")
    business_verification: Optional[BusinessVerificationResult] = Field(
        default=None,
        description="Business context and vendor verification result",
    )
    evaluations: List[FirewallEvaluation] = Field(
        default_factory=list,
        description="Firewall evaluations per step",
    )
    tool_results: List[ToolExecutionResult] = Field(
        default_factory=list,
        description="Mock tool execution outputs",
    )
    overall_decision: PolicyDecision = Field(
        ...,
        description="Aggregate firewall decision for the run",
    )
    explanation: Optional[str] = Field(
        default=None,
        description="Generated explainable security rationale",
    )
    recovery: Optional[RecoveryAction] = Field(
        default=None,
        description="Recommended safe next step",
    )
    evidence_graph: Optional[EvidenceGraph] = Field(
        default=None,
        description="Explainable evidence graph",
    )


# --- Phase 8 Models (Universal Multi-Format Ingestion) ---

class SupportedFormat(str, Enum):
    PDF = "pdf"
    TXT = "txt"
    MD = "md"
    CSV = "csv"
    JSON = "json"
    XML = "xml"
    HTML = "html"
    DOCX = "docx"
    EML = "eml"
    PNG = "png"
    JPG = "jpg"
    JPEG = "jpeg"
    WEBP = "webp"
    UNKNOWN = "unknown"


class UniversalUploadResponse(BaseModel):
    """Structured response from generic multi-format source upload."""
    source_id: str = Field(..., description="Unique provenance source ID")
    filename: str = Field(..., description="Sanitized internal filename")
    original_filename: str = Field(..., description="Original user filename")
    format: str = Field(..., description="Detected format / extension")
    media_type: str = Field(..., description="Detected media type / MIME")
    file_size_bytes: int = Field(..., description="File size in bytes")
    content_hash: str = Field(..., description="SHA-256 cryptographic digest")
    extraction_status: str = Field(..., description="SUCCESS | PARTIAL | OCR_UNAVAILABLE | FAILED")
    extracted_text: str = Field(..., description="Normalized text representation")
    trust_level: TrustLevel = Field(default=TrustLevel.UNTRUSTED_EXTERNAL, description="Trust classification")
    taint_status: TaintStatus = Field(default=TaintStatus.UNTRUSTED, description="Initial taint status")
    extracted_fields: Dict[str, Any] = Field(default_factory=dict, description="Extracted structured fields / metadata")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Parser and document metadata")
    injection_result: Optional[InjectionDetectionResult] = Field(default=None, description="Initial prompt-injection scan")
